name: Publish se.sharp.crypto

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'Crypto/package.json'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    env:
      sub-dir: 'Crypto'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: 'SchroedingerEntertainment'
      - run: npm install
        working-directory: ${{env.sub-dir}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm ci
        working-directory: ${{env.sub-dir}}
      - run: npm publish
        working-directory: ${{env.sub-dir}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
